### ISSUE TITLE
Travis build fails with compilation error

### ISSUE THREAD

**Issue by KochTobi** [qbicsoftware/omero-portlet#12]
The code is fine. The error occurred after updating the `parent-pom`.

The actual cause is `Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded`

**Comment by Steffengreiner** [comment]
After talking with @KochTobi and we agreed that I'll just hijack this issue since the original problem the "objectweb.asm.tree import" was removed from the project. 

Travis now fails due to an OutofMemoryError: 
`Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded`

I had the same issue on my machine and resolved it by switching from adoptopenjdk version `8.0.242.hs-adpt` to the `8.0.265.j9-adpt` version. 
I read online that "J9" is less memory intensive than "hs", so maybe we could try increasing the memory allocation in travis?

**Comment by KochTobi** [comment]
Increase JVM memory to 1GB qbicsoftware/parent-poms#66

solved the issue
